language: r
cache: packages

after_success:
  - Rscript -e 'pkgdown::build_site()'

addons:
  apt:
    packages:
      - libharfbuzz-dev
      - libfribidi-dev

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: main
